language: ruby
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database mentor_pairing_test;' -U postgres
  - bundle exec rake db:migrate
rvm:
  - 1.9.3
  - 2.0.0

notifications:
  email:
    - 'development@devbootcamp.com'
